# Generated by Django 2.0.9 on 2019-03-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
