# Generated by Django 2.1.5 on 2019-03-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0003_menu_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
