# Generated by Django 2.1.5 on 2019-03-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0006_auto_20190314_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='menu_id',
        ),
        migrations.AddField(
            model_name='addcart',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='addcart',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addcart',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
