# Generated by Django 2.1.5 on 2019-03-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0009_auto_20190326_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='cuisines',
            new_name='cuisines1',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisines2',
            field=models.CharField(choices=[('American', 'american'), ('Thai', 'thai'), ('Mexican', 'mexican'), ('chinese', 'Chinese'), ('indian', 'indian'), ('Desert', 'Desert')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
