# Generated by Django 2.1.5 on 2019-03-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0010_auto_20190326_1547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cuisines',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisines1',
            field=models.CharField(choices=[('American', 'american'), ('Thai', 'thai'), ('Mexican', 'mexican'), ('chinese', 'Chinese'), ('indian', 'indian'), ('Desert', 'Desert')], max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisines2',
            field=models.CharField(blank=True, choices=[('American', 'american'), ('Thai', 'thai'), ('Mexican', 'mexican'), ('chinese', 'Chinese'), ('indian', 'indian'), ('Desert', 'Desert')], max_length=10),
        ),
    ]
