# Generated by Django 2.1.5 on 2019-03-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0002_auto_20190302_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image_url',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
