# Generated by Django 2.1.5 on 2019-03-11 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0004_auto_20190306_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADDCART',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restro.Menu')),
                ('restro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restro.Restaurant')),
            ],
        ),
    ]
