# Generated by Django 2.1.5 on 2019-03-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0005_addcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderedby',
        ),
        migrations.RemoveField(
            model_name='order',
            name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='oid',
        ),
        migrations.RemoveField(
            model_name='addcart',
            name='restro_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
