# Generated by Django 2.1.5 on 2019-03-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0007_auto_20190314_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='i',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addcart',
            name='id',
            field=models.CharField(max_length=20),
        ),
    ]
