# Generated by Django 2.1.5 on 2019-04-06 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0011_auto_20190331_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='CART',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restro.Menu')),
            ],
        ),
    ]
