# Generated by Django 2.1.5 on 2019-04-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0012_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ADDCART',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_info',
        ),
        migrations.DeleteModel(
            name='CART',
        ),
    ]
