# Generated by Django 2.1.5 on 2019-04-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0015_auto_20190414_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='CART',
        ),
    ]
