# Generated by Django 2.1.5 on 2019-04-16 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0021_auto_20190416_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='restaurant_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restro.Restaurant'),
            preserve_default=False,
        ),
    ]
