# Generated by Django 2.1.5 on 2019-04-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0022_cart_restaurant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='restaurant_id',
        ),
    ]
