# Generated by Django 2.1.5 on 2019-04-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderplaced_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='pin',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
