# Generated by Django 2.1.5 on 2019-04-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderplaced_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='phone_no',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='street_address',
            field=models.CharField(max_length=150),
        ),
    ]
