# Generated by Django 2.1.5 on 2019-04-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190416_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
    ]
