# Generated by Django 2.2 on 2019-04-16 21:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190416_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
