# Generated by Django 2.2 on 2019-04-16 21:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20190416_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
