# Generated by Django 2.2 on 2019-04-16 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_orderplaced_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='order_id',
        ),
    ]
