# Generated by Django 2.2 on 2019-04-16 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_orderplaced_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.OrderPlaced'),
            preserve_default=False,
        ),
    ]
