# Generated by Django 2.2 on 2019-04-16 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing',
        ),
    ]
